[phases.setup]
nixPkgs = ["...", "nodejs_20"]

[phases.install]
cmds = [
    "...",
    "npm install --prefix script/flunch axios playwright node-imap mailparser imap-simple"
]

[phases.build]
cmds = [
    "...",
    "npx playwright install --with-deps chromium"
]
